apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::043167425407:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1KS4XF3AHX9ZS
      username: system:node:{{EC2PrivateDNSName}}
    - groups: 
      - system:masters
      rolearn: arn:aws:iam::043167425407:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-22T14:16:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1686"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a67e0028-86f3-4170-ba04-9b9039f9edb3
